export const REQ_LOG_TOKEN = 'REQ_LOG_KEY_TOKEN';
export const INFO_LOG_TOKEN = 'INFO_LOG_KEY_TOKEN';
export const CONFIG_SERVICE_TOKEN = 'CONFIG_SERVICE_TOKEN';
export const CHECK_PATH_INTERVAL_TOKEN = 'CHECK_PATH_INTERVAL_TOKEN';
