export const REQ_LOG_TOKEN = Symbol('REQ_LOG_KEY_TOKEN');
export const INFO_LOG_TOKEN = Symbol('INFO_LOG_KEY_TOKEN');
export const CONFIG_SERVICE_TOKEN = Symbol('CONFIG_SERVICE_TOKEN');
export const CHECK_PATH_INTERVAL_TOKEN = Symbol('CHECK_PATH_INTERVAL_TOKEN');
export const LOG_CONFIG_KEY = Symbol('LOG_CONFIG_KEY');
